export const CREATE_ROUTE_SUCCESS = 'CREATE_ROUTE_SUCCESS';
export const READ_ROUTES = 'LOAD_ROUTES';
export const READ_ROUTES_SUCCESS = 'LOAD_ROUTES_SUCCESS';
export const READ_ROUTES_FAIL = 'LOAD_ROUTES_FAIL';
export const UPDATE_ROUTE_SUCCESS = 'UPDATE_ROUTE_SUCCESS';
export const DELETE_ROUTE_SUCCESS = 'DELETE_ROUTE_SUCCESS';
